"""
default_cats.py — Built-in categories that server admins can import into their server.

These are read-only templates; importing one creates a copy in the server's own
category collection that admins can freely edit afterwards.

Keys are the canonical category names (no aliases here — aliases live in the cog).
"""

DEFAULT_CATEGORIES: dict[str, dict] = {
    "rare": {
        "label": "Rare",
        "emoji": "⭐",
        "description": "All legendary, mythical, and ultra-rare Pokémon",
        "pokemon": [
            "10% Zygarde",
            "Arceus",
            "Articuno",
            "Attack Deoxys",
            "Azelf",
            "Blacephalon",
            "Bug Arceus",
            "Bug Silvally",
            "Buzzwole",
            "Calyrex",
            "Celebi",
            "Celesteela",
            "Chi-Yu",
            "Chien-Pao",
            "Cobalion",
            "Complete Zygarde",
            "Cornerstone Mask Ogerpon",
            "Cosmoem",
            "Cosmog",
            "Cresselia",
            "Dada Zarude",
            "Dark Arceus",
            "Dark Silvally",
            "Darkrai",
            "Defense Deoxys",
            "Deoxys",
            "Dialga",
            "Diancie",
            "Dragon Arceus",
            "Dragon Silvally",
            "Drive Mode Miraidon",
            "Electric Arceus",
            "Electric Silvally",
            "Enamorus",
            "Entei",
            "Eternatus",
            "Fairy Arceus",
            "Fairy Silvally",
            "Fezandipiti",
            "Fighting Arceus",
            "Fighting Silvally",
            "Fire Arceus",
            "Fire Silvally",
            "Flying Arceus",
            "Flying Silvally",
            "Galarian Articuno",
            "Galarian Moltres",
            "Galarian Zapdos",
            "Genesect",
            "Ghost Arceus",
            "Ghost Silvally",
            "Giratina",
            "Glastrier",
            "Glide Mode Miraidon",
            "Gliding Build Koraidon",
            "Grass Arceus",
            "Grass Silvally",
            "Groudon",
            "Ground Arceus",
            "Ground Silvally",
            "Guzzlord",
            "Hearthflame Mask Ogerpon",
            "Heatran",
            "High-speed Flight Configuration Genesect",
            "Ho-Oh",
            "Hoopa",
            "Ice Arceus",
            "Ice Silvally",
            "Jirachi",
            "Kartana",
            "Keldeo",
            "Koraidon",
            "Kubfu",
            "Kyogre",
            "Kyurem",
            "Landorus",
            "Latias",
            "Latios",
            "Lugia",
            "Lunala",
            "Magearna",
            "Manaphy",
            "Marshadow",
            "Melmetal",
            "Meloetta",
            "Meltan",
            "Mesprit",
            "Mew",
            "Mewtwo",
            "Miraidon",
            "Moltres",
            "Munkidori",
            "Naganadel",
            "Necrozma",
            "Neutral Xerneas",
            "Nihilego",
            "Ogerpon",
            "Okidogi",
            "Palkia",
            "Pecharunt",
            "Pheromosa",
            "Phione",
            "Pirouette Meloetta",
            "Poipole",
            "Poison Arceus",
            "Poison Silvally",
            "Psychic Arceus",
            "Psychic Silvally",
            "Raikou",
            "Rapid Strike Urshifu",
            "Rayquaza",
            "Regice",
            "Regidrago",
            "Regieleki",
            "Regigigas",
            "Regirock",
            "Registeel",
            "Reshiram",
            "Rock Arceus",
            "Rock Silvally",
            "Shaymin",
            "Silvally",
            "Solgaleo",
            "Spectrier",
            "Speed Deoxys",
            "Sprinting Build Koraidon",
            "Stakataka",
            "Steel Arceus",
            "Steel Silvally",
            "Suicune",
            "Tapu Bulu",
            "Tapu Fini",
            "Tapu Koko",
            "Tapu Lele",
            "Terapagos",
            "Terastal Terapagos",
            "Terrakion",
            "Thundurus",
            "Ting-Lu",
            "Tornadus",
            "Type: Null",
            "Urshifu",
            "Uxie",
            "Victini",
            "Virizion",
            "Volcanion",
            "Water Arceus",
            "Water Silvally",
            "Wellspring Mask Ogerpon",
            "Wo-Chien",
            "Xerneas",
            "Xurkitree",
            "Yveltal",
            "Zacian",
            "Zamazenta",
            "Zapdos",
            "Zarude",
            "Zekrom",
            "Zenith Marshadow",
            "Zeraora",
            "Zygarde",
            "Zygarde Cell",
            "Zygarde Core",
        ],
    },
    "regional": {
        "label": "Regional",
        "emoji": "🌍",
        "description": "All regional variant Pokémon (Alolan, Galarian, Hisuian, Paldean)",
        "pokemon": [
            "Alolan Diglett",
            "Alolan Dugtrio",
            "Alolan Exeggutor",
            "Alolan Geodude",
            "Alolan Golem",
            "Alolan Graveler",
            "Alolan Grimer",
            "Alolan Marowak",
            "Alolan Meowth",
            "Alolan Muk",
            "Alolan Ninetales",
            "Alolan Persian",
            "Alolan Raichu",
            "Alolan Raticate",
            "Alolan Rattata",
            "Alolan Sandshrew",
            "Alolan Sandslash",
            "Alolan Vulpix",
            "Aqua Breed Tauros",
            "Blaze Breed Tauros",
            "Combat Breed Tauros",
            "Cursola",
            "Galarian Articuno",
            "Galarian Corsola",
            "Galarian Darmanitan",
            "Galarian Darumaka",
            "Galarian Farfetch'd",
            "Galarian Linoone",
            "Galarian Meowth",
            "Galarian Moltres",
            "Galarian Mr. Mime",
            "Galarian Ponyta",
            "Galarian Rapidash",
            "Galarian Slowbro",
            "Galarian Slowking",
            "Galarian Slowpoke",
            "Galarian Stunfisk",
            "Galarian Weezing",
            "Galarian Yamask",
            "Galarian Zapdos",
            "Galarian Zen Darmanitan",
            "Galarian Zigzagoon",
            "Hisuian Arcanine",
            "Hisuian Avalugg",
            "Hisuian Braviary",
            "Hisuian Decidueye",
            "Hisuian Electrode",
            "Hisuian Goodra",
            "Hisuian Growlithe",
            "Hisuian Lilligant",
            "Hisuian Qwilfish",
            "Hisuian Samurott",
            "Hisuian Sliggoo",
            "Hisuian Sneasel",
            "Hisuian Typhlosion",
            "Hisuian Voltorb",
            "Hisuian Zoroark",
            "Hisuian Zorua",
            "Mr. Rime",
            "Obstagoon",
            "Overqwil",
            "Paldean Wooper",
            "Perrserker",
            "Runerigus",
            "Sirfetch'd",
            "Sneasler",
        ],
    },
    "paradox": {
        "label": "Paradox",
        "emoji": "🐟",
        "description": "All Paradox except Rare",
        "pokemon": [
            "Brute Bonnet","Flutter Mane","Slither Wing","Sandy Shocks","Iron Jugulis","Roaring Moon","Iron Valiant","Walking Wake","Gouging Fire","Scream Tail","Iron Treads","Iron Bundle","Iron Thorns","Iron Leaves","Raging Bolt","Great Tusk","Iron Hands","Iron Moth","Iron Boulder","Iron Crown",

        ],    
    },
    "eevee": {
        "label": "Eevee",
        "emoji": "🦊",
        "description": "All Eeveelutions except Eevee",
        "pokemon": [
           "Partner Eevee","Vaporeon","Jolteon","Flareon","Umbreon","Leafeon","Glaceon","Sylveon","Espeon",
        ],        
    },
    "gigantamax": {
        "label": "Gigantamax",
        "emoji": "🔆",
        "description": "All Pokémon with a Gigantamax form",
        "pokemon": [
            "Alcremie",
            "Amped Toxtricity",
            "Appletun",
            "Blastoise",
            "Butterfree",
            "Centiskorch",
            "Charizard",
            "Cinderace",
            "Coalossal",
            "Copperajah",
            "Corviknight",
            "Drednaw",
            "Duraludon",
            "Eevee",
            "Eternatus",
            "Flapple",
            "Garbodor",
            "Gengar",
            "Grimmsnarl",
            "Hatterene",
            "Inteleon",
            "Kingler",
            "Lapras",
            "Low Key Toxtricity",
            "Machamp",
            "Melmetal",
            "Meowth",
            "Orbeetle",
            "Pikachu",
            "Rapid Strike Urshifu",
            "Rillaboom",
            "Sandaconda",
            "Snorlax",
            "Urshifu",
            "Vanilla Cream Berry Sweet Alcremie",
            "Vanilla Cream Clover Sweet Alcremie",
            "Vanilla Cream Flower Sweet Alcremie",
            "Vanilla Cream Love Sweet Alcremie",
            "Vanilla Cream Ribbon Sweet Alcremie",
            "Vanilla Cream Star Sweet Alcremie",
            "Venusaur",
        ],
    },
}
